import { hotDogs, burgers, sandwiches, chorrillanas, sides, drinks, breakfasts, kidsMenu } from '../data/products';

export const menuCategories = [
  {
    id: 'hot-dogs',
    icon: 'hot_tub',
    title: 'Completos',
    products: hotDogs,
    category: 'Completos',
    categoryKey: 'hotDogs',
    layout: 'vertical',
    gridCols: 'grid-cols-1 md:grid-cols-2 lg:grid-cols-3',
    initialVisibleCount: 3,
  },
  {
    id: 'burgers',
    icon: 'lunch_dining',
    title: 'BURGERS',
    products: burgers,
    category: 'Burgers',
    categoryKey: 'burgers',
    layout: 'horizontal',
    gridCols: 'grid-cols-1 md:grid-cols-2',
    initialVisibleCount: 2,
  },
  {
    id: 'sandwiches',
    icon: 'lunch_dining',
    title: 'SANDWICHES',
    products: sandwiches,
    category: 'Sandwiches',
    categoryKey: 'sandwiches',
    layout: 'vertical',
    gridCols: 'grid-cols-1 md:grid-cols-2 lg:grid-cols-3',
    initialVisibleCount: 3,
  },
  {
    id: 'chorrillanas',
    icon: 'dinner_dining',
    title: 'CHORRILLANAS',
    products: chorrillanas,
    category: 'Chorrillanas',
    categoryKey: 'chorrillanas',
    layout: 'horizontal',
    gridCols: 'grid-cols-1 md:grid-cols-2',
    initialVisibleCount: 2,
  },
  {
    id: 'breakfasts',
    icon: 'breakfast_dining',
    title: 'DESAYUNOS',
    products: breakfasts,
    category: 'Desayunos',
    categoryKey: 'breakfasts',
    layout: 'vertical',
    gridCols: 'grid-cols-1 md:grid-cols-2 lg:grid-cols-3',
    initialVisibleCount: 3,
  },
  {
    id: 'kids-menu',
    icon: 'child_care',
    title: 'MENÚ KIDS',
    products: kidsMenu,
    category: 'Menú Kids',
    categoryKey: 'kidsMenu',
    layout: 'vertical',
    gridCols: 'grid-cols-1 md:grid-cols-3',
    initialVisibleCount: 3,
  },
  {
    id: 'fries',
    icon: 'restaurant',
    title: 'Complementos',
    products: sides,
    category: 'Sides',
    categoryKey: 'sides',
    layout: 'compact',
    gridCols: 'grid-cols-1 md:grid-cols-3',
    initialVisibleCount: 3,
    gap: 'gap-6',
    centered: true,
  },
  {
    id: 'drinks',
    icon: 'local_drink',
    title: 'BEBIDAS',
    products: drinks,
    category: 'Bebidas',
    categoryKey: 'drinks',
    layout: 'icon',
    gridCols: 'grid-cols-2 md:grid-cols-4 lg:grid-cols-6',
    initialVisibleCount: 6,
    gap: 'gap-4',
  },
];

